-- CREATE TABLE IF NOT EXISTS DEPARTMENT (
-- EMPLOYEE_ID TEXT,
-- NAME TEXT,
-- DEPARTMENT_ID TEXT,
-- MANAGER_ID TEXT,
-- SALARY REAL );
-- INSERT INTO DEPARTMENT (EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY) VALUES
-- ("1", "Zareen", "90", "100", 24000),
-- ("2", "Junaid", "78", "101", 25000),
-- ("3", "Azrin", "90", "102", 26000),
-- ("4", "Mahjabeen", "60", "101", 27000),
-- ("5", "Nashmia", "78", "102", 28000),
-- ("6", "Tasneem", "60", "100", 29000);
-- SELECT * FROM DEPARTMENT
-- SELECT DEPARTMENT_ID AS "DEPARTMENT CODE",
-- COUNT(*) AS "NUMBER OF EMPLOYEES" FROM DEPARTMENT
-- GROUP BY DEPARTMENT_ID
-- SELECT DEPARTMENT_ID AS "DEPARTMENT CODE",
-- COUNT(*) AS "NUMBER OF EMPLOYEES",
-- SUM(SALARY) AS "TOTAL OF SALARY"
-- FROM DEPARTMENT
-- GROUP BY DEPARTMENT_ID;
-- SELECT DEPARTMENT_ID, SUM(SALARY)
-- FROM DEPARTMENT
-- GROUP BY DEPARTMENT_ID;
-- SELECT DEPARTMENT_ID AS "DEPARTMENT CODE",
-- SUM(SALARY) AS "TOTAL OF SALARY"
-- FROM DEPARTMENT
-- WHERE MANAGER_ID = "101"
-- GROUP BY DEPARTMENT_ID;
SELECT DEPARTMENT_ID, COUNT(*) AS "NUMBER OF EMPLOYEES"
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;
HAVING COUNT(*)> 2





